### PR TITLE
Declaration run through edits 280815

### PR DESCRIPTION
**Pull request by superroz**
added hint text to be consistent with earlier similar questions.

### CODE REVIEW

**Comment by TheDoubleK** [comment]
:+1:

**Comment by superroz** [comment]
1 more update to hint text.

**Comment by TheDoubleK** [comment]
Can we not have "TICK ALL THE BOXES" as the hint text for that one?

**Comment by TheDoubleK** [comment]
:+1:

**Comment by superroz** [comment]
I’d like to keep ’select’ to be consistent with the 17 other similar questions in the declaration and the ITT documentation. 

Happy to change ‘each' to ‘all’ . I’ll have to update question 7 too.

I don’t know what the legal position is on directing people to tick all questions without clarifying - it could be read as though we told people to tick whether they comply or not.

**Comment by TheDoubleK** [comment]
No I was only joking! I think it's OK.

**Comment by superroz** [comment]
Phew!

**Comment by ralph-hawkins** [comment]
Words look good. If we had time, I’d fix the inverted commas and apostrophes. Maybe for DS3.

:+1:

**Pull request merged**
